package analyze

import (
	"context"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

const (
	allPackages = "./..."
	ifStatement = "IfStmt"
	rangeStmt   = "RangeStmt"
	assignStmt  = "AssignStmt"
	returnStmt  = "ReturnStmt"
)

func moduleFixture(t *testing.T, sample string) string {
	t.Helper()

	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "go.mod"), "module example\n\ngo 1.26\n")
	writeTestFile(t, filepath.Join(root, "sample.go"), sample)

	return root
}

func scanFixture(t *testing.T, root string, includeGenerated bool) ScanResult {
	t.Helper()

	scanned, err := Scan(context.Background(), ScanOptions{
		Root:             root,
		Patterns:         []string{allPackages},
		MinLines:         4,
		IncludeGenerated: includeGenerated,
	})
	if err != nil {
		t.Fatal(err)
	}

	return scanned
}

func TestScan(t *testing.T) {
	t.Parallel()

	root := moduleFixture(t, `package example

type worker struct{}

func tiny() {}

func (worker) Run(value int) error {
	if value > 0 {
		return nil
	}
	return os.ErrInvalid
}
`)
	scanned := scanFixture(t, root, false)
	if len(scanned.Functions) != 1 {
		t.Fatalf("got %d functions, want 1", len(scanned.Functions))
	}
	function := scanned.Functions[0]
	if function.Name != "worker.Run" {
		t.Fatalf("name = %q", function.Name)
	}
	if function.File != "sample.go" || function.Line != 7 {
		t.Fatalf("location = %s:%d", function.File, function.Line)
	}
	if len(function.Calls) != 0 {
		t.Fatalf("calls = %v", function.Calls)
	}
	if function.NodeCounts[ifStatement] != 1 {
		t.Fatalf("nodes = %v", function.NodeCounts)
	}
}

func TestScanIncludesRepositoryTestsWithoutSyntheticFiles(t *testing.T) {
	t.Parallel()

	root := moduleFixture(t, `package example

func Production(value int) int {
	if value < 0 {
		return -value
	}
	return value
}
`)
	writeTestFile(t, filepath.Join(root, "sample_test.go"), `package example

import "testing"

func TestProduction(t *testing.T) {
	t.Parallel()
	if Production(-1) != 1 {
		t.Fatal("unexpected result")
	}
}
`)

	scanned, err := Scan(context.Background(), ScanOptions{
		Root: root, Patterns: []string{allPackages}, MinLines: 4, MinNodes: 3, IncludeTests: true,
	})
	if err != nil {
		t.Fatal(err)
	}

	names := make([]string, 0, len(scanned.Functions))
	for _, function := range scanned.Functions {
		names = append(names, function.Name)
		if !filepath.IsLocal(function.File) {
			t.Fatalf("non-local source was scanned: %s", function.File)
		}
	}
	if !slices.Contains(names, "Production") || !slices.Contains(names, "TestProduction") {
		t.Fatalf("functions = %v", names)
	}
}

func TestScanSkipsGeneratedFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "go.mod"), "module example\n\ngo 1.26\n")
	body := `
func Handle(value int) error {
	if value > 0 {
		return nil
	}
	return nil
}
`
	writeTestFile(t, filepath.Join(root, "hand.go"), "package example\n"+body)
	writeTestFile(
		t, filepath.Join(root, "wire.go"),
		"// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage example\n"+body,
	)
	scanned := scanFixture(t, root, false)
	if len(scanned.Functions) != 1 || scanned.Functions[0].File != "hand.go" {
		t.Fatalf("functions = %v", scanned.Functions)
	}
	if len(scanned.Generated) != 1 || scanned.Generated[0] != "wire.go" {
		t.Fatalf("generated = %v", scanned.Generated)
	}
	kept := scanFixture(t, root, true)
	if len(kept.Functions) != 2 || len(kept.Generated) != 0 {
		t.Fatalf("include-generated kept %d functions, %d generated", len(kept.Functions), len(kept.Generated))
	}
}

func TestScanSkipsIgnoredFunctions(t *testing.T) {
	t.Parallel()

	root := moduleFixture(t, `package example

// Kept does work.
func Kept(value int) error {
	if value > 0 {
		return nil
	}
	return nil
}

// Retired duplicates Kept on purpose.
// similarity:ignore
func Retired(value int) error {
	if value > 0 {
		return nil
	}
	return nil
}
`)
	scanned := scanFixture(t, root, false)
	if len(scanned.Functions) != 1 || scanned.Functions[0].Name != "Kept" {
		t.Fatalf("functions = %v", scanned.Functions)
	}
	if len(scanned.Ignored) != 1 {
		t.Fatalf("ignored = %v", scanned.Ignored)
	}
}

func TestRank(t *testing.T) {
	t.Parallel()

	functions := []Function{
		{ID: "a", Calls: []string{"decode", "read"}, NodeCounts: map[string]int{ifStatement: 1, returnStmt: 2}},
		{ID: "b", Calls: []string{"decode", "write"}, NodeCounts: map[string]int{ifStatement: 1, returnStmt: 2}},
		{ID: "c", Calls: []string{"close"}, NodeCounts: map[string]int{"ForStmt": 1}},
	}
	embeddings := [][]float32{{1, 0}, {1, 0}, {0, 1}}
	candidates, err := Rank(functions, embeddings, 0.8, 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(candidates) != 1 {
		t.Fatalf("got %d candidates, want 1", len(candidates))
	}
	candidate := candidates[0]
	if candidate.Left.ID != "a" || candidate.Right.ID != "b" {
		t.Fatalf("pair = %s, %s", candidate.Left.ID, candidate.Right.ID)
	}
	if candidate.StructureScore != 1 || candidate.CallScore != 1.0/3.0 {
		t.Fatalf("scores = %v, %v", candidate.StructureScore, candidate.CallScore)
	}
}

func TestRankKeepsAFunctionsOwnBestMatchAgainstHigherScoringPairs(t *testing.T) {
	t.Parallel()

	functions := []Function{{ID: "a"}, {ID: "b"}, {ID: "c"}, {ID: "d"}, {ID: "e"}}
	embeddings := [][]float32{
		{1, 0, 0, 0},
		{0.6, 0.8, 0, 0},
		{0, 0, 1, 0},
		{0, 0, 0.99, 0.141},
		{0, 0, 0.98, 0.199},
	}

	candidates, err := Rank(functions, embeddings, 0.5, 3)
	if err != nil {
		t.Fatal(err)
	}

	pairs := make([]string, 0, len(candidates))
	for _, candidate := range candidates {
		pairs = append(pairs, candidate.Left.ID+candidate.Right.ID)
	}
	if !slices.Contains(pairs, "ab") {
		t.Fatalf("pairs = %v, want the ab pair: a and b are each other's best match at 0.6, "+
			"and a cut on absolute score drops them behind the c, d, e cluster near 0.99", pairs)
	}
}

func TestSeparationMeasuresTheGapBelowEachNeighbour(t *testing.T) {
	t.Parallel()

	row := []neighbour{{score: 0.9}, {score: 0.5}, {score: 0.45}, {score: 0.4}}
	separate(row)

	if !(row[0].separation > row[1].separation) {
		t.Errorf("separations = %v, want the standout neighbour above the plateau", row)
	}
	if row[len(row)-1].separation != 0 {
		t.Errorf("last separation = %v, want 0: nothing follows it", row[len(row)-1].separation)
	}
}

func TestSeparationIgnoresTheScoreFloorWhenShapingTheDistribution(t *testing.T) {
	t.Parallel()

	functions := []Function{{ID: "a"}, {ID: "b"}, {ID: "c"}, {ID: "d"}}
	embeddings := [][]float32{
		{1, 0, 0},
		{0.8, 0.6, 0},
		{0.2, 0, 0.9797},
		{0.1, 0, 0.995},
	}

	candidates, err := Rank(functions, embeddings, 0.7, 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(candidates) == 0 {
		t.Fatal("no candidates survived the floor")
	}
	for _, candidate := range candidates {
		if candidate.Separation == 0 {
			t.Errorf("pair %s/%s has no separation: the floor left too few neighbours to measure against",
				candidate.Left.ID, candidate.Right.ID)
		}
	}
}

func TestSequenceSimilaritySeparatesNestingThatCountsCannot(t *testing.T) {
	t.Parallel()

	outerIf := Function{
		NodeCounts:   map[string]int{ifStatement: 1, rangeStmt: 1, assignStmt: 1},
		NodeSequence: []string{ifStatement, rangeStmt, assignStmt},
	}
	outerRange := Function{
		NodeCounts:   map[string]int{ifStatement: 1, rangeStmt: 1, assignStmt: 1},
		NodeSequence: []string{rangeStmt, ifStatement, assignStmt},
	}
	if structure := histogramCosine(outerIf.NodeCounts, outerRange.NodeCounts); structure != 1 {
		t.Fatalf("node mix should not separate these, got %v", structure)
	}
	sequence := SequenceSimilarity(outerIf, outerRange)
	if sequence >= 1 {
		t.Fatalf("sequence score did not separate the pair, got %v", sequence)
	}
	identical := SequenceSimilarity(outerIf, outerIf)
	if identical != 1 {
		t.Fatalf("identical sequences scored %v", identical)
	}
}

func TestSequenceSimilarityDeclinesOversizedFunctions(t *testing.T) {
	t.Parallel()

	huge := Function{NodeSequence: make([]string, maximumSequenceNodes+1)}
	if score := SequenceSimilarity(huge, huge); score != 0 {
		t.Fatalf("oversized pair scored %v, want 0", score)
	}
}

func TestTokenChunks(t *testing.T) {
	t.Parallel()

	source := "func add(a, b int) int { return a + b }"
	chunks := TokenChunks(source, 5, 5)
	if len(chunks) < 2 {
		t.Fatalf("got %d chunks", len(chunks))
	}
	if chunks[0] == source {
		t.Fatal("source was not split")
	}
	if whole := TokenChunks(source, 5, 100); len(whole) != 1 || whole[0] != source {
		t.Fatalf("whole = %v", whole)
	}
}

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func TestFunctionSourceDropsInlineCommentsButKeepsDirectives(t *testing.T) {
	t.Parallel()

	root := moduleFixture(t, `package example

func Handle(value int) error {
	// this explanation should not reach the embedding
	if value > 0 {
		return nil // trailing note
	}
	//go:noinline
	return nil
}
`)
	scanned := scanFixture(t, root, false)
	if len(scanned.Functions) != 1 {
		t.Fatalf("functions = %v", scanned.Functions)
	}
	source := scanned.Functions[0].Source
	for _, dropped := range []string{"this explanation", "trailing note"} {
		if strings.Contains(source, dropped) {
			t.Fatalf("comment survived into the embedding text: %q", source)
		}
	}
	if !strings.Contains(source, "//go:noinline") {
		t.Fatalf("directive was stripped: %q", source)
	}
	if !strings.Contains(source, "if value > 0") {
		t.Fatalf("code was lost: %q", source)
	}
}

func TestScanSkipsFunctionsBelowNodeThreshold(t *testing.T) {
	t.Parallel()

	root := moduleFixture(t, `package example

func Wide(
	first int,
	second int,
	third int,
) int {
	return first + second + third
}

func Real(values []int) int {
	total := 0
	for _, value := range values {
		total += value
	}
	return total
}
`)
	scanned, err := Scan(context.Background(), ScanOptions{
		Root: root, Patterns: []string{allPackages}, MinLines: 4, MinNodes: 3,
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(scanned.Functions) != 1 || scanned.Functions[0].Name != "Real" {
		t.Fatalf("node threshold did not drop the one-statement function: %v", scanned.Functions)
	}
}

func TestScanDetectsGeneratorsThatSkipTheStrictHeader(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "go.mod"), "module example\n\ngo 1.26\n")
	writeTestFile(t, filepath.Join(root, "easy.go"), `// AUTOGENERATED FILE: easyjson marshaler

package example

func Marshal(value int) error {
	if value > 0 {
		return nil
	}
	return nil
}
`)
	scanned := scanFixture(t, root, false)
	if len(scanned.Generated) != 1 {
		t.Fatalf("lax generated marker was not detected: %+v", scanned)
	}
}

func TestSizeRatioComparesStatementCounts(t *testing.T) {
	t.Parallel()

	small := Function{ID: "a", NodeSequence: make([]string, 4)}
	large := Function{ID: "b", NodeSequence: make([]string, 16)}
	if got := Compare(small, large, 0.9).SizeRatio; got != 0.25 {
		t.Fatalf("size ratio = %v, want 0.25", got)
	}
	if got := Compare(small, small, 0.9).SizeRatio; got != 1 {
		t.Fatalf("identical sizes scored %v", got)
	}
}
